spring:
  application:
    name: "hikaribase"
  ai:
    model:
      chat: none # disable auto-configured chat provider
    chat:
      client:
        enabled: false # disable ChatClient bean auto-creation
  datasource:
    url: "jdbc:sqlite:./data/app.db"
    driver-class-name: org.sqlite.JDBC
  config:
    import:
      - 'classpath:secrets.properties'